// C:\NexPulse\backend\src\constants\misHeadings.js

import { sanitizeHeading } from "../utils/misUtils.js";

/**
 * ORIGINAL headings exactly from master sheet
 * (124 headings)
 */
export const RAW_MIS_HEADINGS = [
  "Sr No.",
  "Scheme/Program/Model",
  "Sub Scheme",
  "Sector /SSC Name",
  "Batch Type",
  "Batch Id",
  "SSTPL Spoc Name",
  "Batch Name",
  "Assessment Type",
  "Mode Of Assessment",
  "Job Role Name",
  "Job Role Code",
  "Job Role Level",
  "Job RoleVersion",
  "Preferred Assessment Language",
  "Batch Size",
  "Enrolled Candidates",
  "Dropout Candidates Size",
  "Eligible Candidates Size",
  "No.of Women Learners Enrolled",
  "TP Name",
  "TP ID",
  "TC Name",
  "TC ID",
  "Traning Center Address (TC)",
  "TC District",
  "TC State",
  "TC Pin Code",
  "TP Spoc Name",
  "TP Spoc No.",
  "TP Spoc Email",
  "Batch Start Date",
  "Batch End Date",
  "Assessment Date As Per Sidh",
  "Final Assessment Date",
  "Batch Duration",
  "Day of Assessment",
  "Source Of Batch Received",
  "Date Of Batch Received",
  "Assessor Name",
  "Assessor Contact No.",
  "Assessor Email ID",
  "Assessor AR ID",
  "AR Password",
  "Trainer Name",
  "Trainer ID",
  "Assessment Status",
  "Assessment Remarks",
  "Present Candidate",
  "Absent Candidate",
  "Pass Candidates",
  "Fail Candidate",
  "Total Male Candidates to be assessed",
  "Total Female Candidates to be assessed",
  "Passing Percentage Of Result",
  "Result Status",
  "Result Remarks",
  "Date Of Result Upload On Sidh",
  "Council / Source",
  "Batch Received Month",
  "Parent Batch Id",
  "Theory/OJT",
  "Received Through SIP/LMS Portal",
  "Batch Category",
  "Project",
  "Course Code",
  "Course Level",
  "Course Category",
  "VTP Contact No.",
  "Final Scheduling Date",
  "Month of Assessed Batch",
  "Revised Date",
  "Assessment Start Time",
  "Assessment End Time",
  "Candidates Registered",
  "Average % Marks Obtained (Less than or equal to 100% )",
  "Coordinator Name",
  "Coordinator Contact",
  "Coordinator Email",
  "Assessor Qualification",
  "Proctor Name",
  "Proctor No.",
  "Date Result Received from Assessor",
  "Result Submission Date",
  "Result Approval Date",
  "Was there a certified trainer",
  "Upload date on SDMS / LMS",
  "Rate",
  "AB Share",
  "Total",
  "Documents submit to finance for Invoicing",
  "Invoice Reference",
  "Invoice Amount",
  "Date of Invoice",
  "Invoice to Council",
  "Remarks",
  "Date Payment Received",
  "Payment Ref.",
  "Amount Received",
  "TDS Amount",
  "Pending Payment",
  "Assessor's Rate",
  "Assessor Payment",
  "Assessor Invoice Received Status",
  "Assessor Invoice to finance",
  "Assessor Invoice Ref.",
  "Amount Paid to Assessor",
  "Date Amount Paid",
  "Date Hard Copies received",
  "Attendance Sheet",
  "Documents",
  "Evidences",
  "Remark",
  "Status as SIP/LMS Per Portal",
  "Batch Conducted On",
  "LMS Batches",
  "Audit Status",
  "DBMS Batches",
  "Status",
  "Uploaded Person Name",
  "Uploaded Date",
  "SDMIS Portal",
  "Audit link",
  "Document Status"
];

/**
 * SANITIZED headings to store inside MongoDB Map safely
 * (removes dots, spaces, /, (), etc.)
 */
export const MIS_MASTER_HEADINGS = RAW_MIS_HEADINGS.map(h =>
  sanitizeHeading(h)
);
