export const PERMISSIONS = {
  EMPLOYEE_DIRECTORY: "EMPLOYEE_DIRECTORY",

  ATTENDANCE_MARK: "ATTENDANCE_MARK",
  ATTENDANCE_VIEW: "ATTENDANCE_VIEW",
  ATTENDANCE_MANAGE: "ATTENDANCE_MANAGE",

  TASK_UPDATE: "TASK_UPDATE",
  TASK_VIEW: "TASK_VIEW",
  TASK_ASSIGN: "TASK_ASSIGN",
  TASK_INBOX: "TASK_INBOX",

  MIS_MANAGE: "MIS_MANAGE",

  SALARY_VIEW: "SALARY_VIEW",
  SALARY_MANAGE: "SALARY_MANAGE",
  GEN_SALARY_SLIP: "GEN_SALARY_SLIP",

  UPLOAD_DOCUMENTS: "UPLOAD_DOCUMENTS",
  HOLIDAYS_VIEW: "HOLIDAYS_VIEW",
  HOLIDAYS_MARK: "HOLIDAYS_MARK",

  LEAVE_REQUEST: "LEAVE_REQUEST",
  LEAVE_APPROVAL: "LEAVE_APPROVAL",

  BELL_RING: "BELL_RING",

  CHAT_EMPLOYEE: "CHAT_EMPLOYEE",
  CHAT_ADMIN: "CHAT_ADMIN",
};
